site_name: "ICBO-2022: International Conference on Biomedical Ontology"
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Call for Submissions: call-for-submissions.md
  - Journal of Biomedical Semantics ICBO Thematic Series: submit-jbms-icbo.md
  - Michigan Week of Ontology and Semantic Web: michigan-week-of-ontology-and-semantic-web.md 
  - Contact Information: contact-information.md
  - Co-organizers: co-organizers.md
