site_name: "ICBO-2022: International Conference on Biomedical Ontology"
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Call for Submissions: call-for-submissions.md
  - Contact Information: contact-information.md
  - Co-organizers: co-organizers.md